services:

  jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "bundle install && jekyll serve --watch --force_polling --port 4042 --config '_config.yml,_config_dev.yml'"

    volumes:
      - ./:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "4042:4042"
    working_dir: /app
    environment:
      JEKYLL_ENV: development
      BUNDLE_PATH: /usr/local/bundle

volumes:
  bundle_cache: