#!/usr/bin/env python3
"""Generate _data/playbook.yml from the repo's prompt and instruction files.

Scans:
  .github/prompts/*.prompt.md            -> frontmatter (mode, description) + first H1
  .github/instructions/*.instructions.md -> frontmatter (applyTo, description) + first H1

Emits _data/playbook.yml with two sorted arrays (prompts, instructions) so
Jekyll pages can loop over them via site.data.playbook.prompts and
site.data.playbook.instructions.

Design constraints:
  - Standard library only (no PyYAML). Frontmatter is parsed with a small
    top-level "key: value" reader, and the output YAML is emitted by hand
    with double-quoted, escaped scalars.
  - Deterministic: entries are sorted by file path and no timestamps are
    written, so re-running on unchanged inputs produces identical bytes.

Usage:
  python3 scripts/generate_playbook_data.py          # writes _data/playbook.yml
  python3 scripts/generate_playbook_data.py --check  # exit 1 if file is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROMPTS_DIR = REPO_ROOT / ".github" / "prompts"
INSTRUCTIONS_DIR = REPO_ROOT / ".github" / "instructions"
OUTPUT_FILE = REPO_ROOT / "_data" / "playbook.yml"

H1_RE = re.compile(r"^#\s+(.+?)\s*$")


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter dict, body) for a file with a leading YAML block.

    Only top-level scalar "key: value" pairs are read, which covers the
    canonical schema in .github/FRONTMATTER.md (mode, description, applyTo,
    date, lastmod). Files without a frontmatter block yield an empty dict.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    fm: dict[str, str] = {}
    body_start = len(lines)
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            body_start = i + 1
            break
        match = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if match:
            key, value = match.group(1), match.group(2).strip()
            if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
                value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            elif len(value) >= 2 and value[0] == "'" and value[-1] == "'":
                value = value[1:-1].replace("''", "'")
            fm[key] = value
    body = "\n".join(lines[body_start:])
    return fm, body


def first_h1(body: str) -> str | None:
    """Return the text of the first Markdown H1 in body, if any."""
    in_fence = False
    for line in body.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = H1_RE.match(line)
        if match:
            return match.group(1)
    return None


def fallback_name(path: Path, suffix: str) -> str:
    """Derive a sentence-case name from a filename like article-review.prompt.md."""
    stem = path.name
    if stem.endswith(suffix):
        stem = stem[: -len(suffix)]
    words = stem.replace("-", " ").replace("_", " ").strip()
    return words[:1].upper() + words[1:] if words else stem


def yaml_quote(value: str) -> str:
    """Emit a YAML double-quoted scalar with backslash and quote escaping."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def collect(directory: Path, suffix: str, extra_key: str) -> list[dict[str, str]]:
    """Build sorted entry dicts for every *{suffix} file in directory."""
    entries: list[dict[str, str]] = []
    for path in sorted(directory.glob(f"*{suffix}")):
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        entries.append(
            {
                "name": first_h1(body) or fallback_name(path, suffix),
                "file": path.relative_to(REPO_ROOT).as_posix(),
                "description": fm.get("description", ""),
                extra_key: fm.get(extra_key, ""),
            }
        )
    return entries


def render(prompts: list[dict[str, str]], instructions: list[dict[str, str]]) -> str:
    lines = [
        "# Generated by scripts/generate_playbook_data.py — do not edit by hand.",
        "# Regenerate after adding or editing files in .github/prompts/ or",
        "# .github/instructions/ with:  python3 scripts/generate_playbook_data.py",
        "prompts:",
    ]
    for entry in prompts:
        lines.append(f"  - name: {yaml_quote(entry['name'])}")
        lines.append(f"    file: {yaml_quote(entry['file'])}")
        lines.append(f"    description: {yaml_quote(entry['description'])}")
        lines.append(f"    mode: {yaml_quote(entry['mode'])}")
    lines.append("instructions:")
    for entry in instructions:
        lines.append(f"  - name: {yaml_quote(entry['name'])}")
        lines.append(f"    file: {yaml_quote(entry['file'])}")
        lines.append(f"    description: {yaml_quote(entry['description'])}")
        lines.append(f"    applyTo: {yaml_quote(entry['applyTo'])}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    prompts = collect(PROMPTS_DIR, ".prompt.md", "mode")
    instructions = collect(INSTRUCTIONS_DIR, ".instructions.md", "applyTo")
    output = render(prompts, instructions)

    if "--check" in argv:
        current = OUTPUT_FILE.read_text(encoding="utf-8") if OUTPUT_FILE.exists() else ""
        if current != output:
            print(f"STALE: {OUTPUT_FILE.relative_to(REPO_ROOT)} does not match sources.")
            print("Run: python3 scripts/generate_playbook_data.py")
            return 1
        print(f"OK: {OUTPUT_FILE.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(
        f"Wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}: "
        f"{len(prompts)} prompts, {len(instructions)} instruction files."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
